#!/bin/bash -e

# STSBL Repository Configuration Program
# Copyright (C) 2016 Felix Jacobi
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# use translations from iserv
export BASHGT_DOMAIN=iserv

# source common library
. /usr/lib/iserv/stsblrepocfg-common

# source bash-gettext library
. /usr/lib/bash-gettext/functions.sh

# Prints out the program help
echoHelp() {
  echo $(_ "Usement:")
  echo "  stsbl-umode"
  echo "  $(_ "Print current update mode and exit.")"
  echo
  echo "  stsbl-umode [ stable | testing | unstable ]"
  echo "  $(_ "Set a new update mode.")"
  echo
  echo "  stsbl-umode --help"
  echo "  $(_ "Print out this help and exit.")"
}

# super user check
if [ $UID != 0 ]; then
  echo $(_ "Root rights are required to run this program.") >&2
  exit 1
fi

# Checking number of arguments
if [ "$#" -gt 1 ] || [ "$#" -lt 0 ]
then
  echo $(_ "Wrong number of arguments.") >&2
  echo >&2
  echoHelp >&2
  exit 1
fi

if [ "$1" = "--help" ]
then
  echoHelp
  exit 0
fi

# source config
. /usr/lib/iserv/stsblrepocfg

OLDUPDATEMODE="$REPOUPDATEMODE"
NEWUPDATEMODE="$1"

case "$NEWUPDATEMODE" in
  "s")
    NEWUPDATEMODE=stable
    ;;
  "t")
    NEWUPDATEMODE=testing
    ;;
  "u")
    NEWUPDATEMODE=unstable
    ;;
esac
    
if [ "$#" = 0 ]
then
  echo $(__ "The current update mode is %s." "$OLDUPDATEMODE")
  exit 0
fi

if [ "$NEWUPDATEMODE" = "$OLDUPDATEMODE" ]
then
  echo $(__ "The update mode will keep the value %s." "$NEWUPDATEMODE")
  exit 0
elif [ "$NEWUPDATEMODE" = "stable" ] || [ "$NEWUPDATEMODE" = "testing" ] || [ "$NEWUPDATEMODE" = "unstable" ]
then
  echo "$OLDUPDATEMODE -> $NEWUPDATEMODE"
else
  echo $(__ "Unknown update mode %s." "$NEWUPDATEMODE") >&2
  echo >&2
  echoHelp >&2
  exit 1
fi

# assign values for storing
CUSTOMERNUMBER=$REPOCUSTOMERNUMBER
UPDATEMODE=$NEWUPDATEMODE
PASSWORD=$REPOPASSWORD

storeConfig
iservchk apt
exit 0
