#!/bin/bash -e

export LC_ALL=C

iconf repair /etc/apt/sources.list.d/stsbl.list

if [ ! -e "/var/lib/stsbl/" ]
then
  mkdir /var/lib/stsbl/
  chmod 0755 /var/lib/stsbl/
  echo "/var/lib/stsbl/ created."
else
  echo "/var/lib/stsbl/ was ok."
fi

if [ $(stat -c "%a" /var/lib/stsbl/) != "755" ]
then
  chmod 0755 /var/lib/stsbl/
  echo "/var/lib/stsbl/ permissions changed to 755."
else
  echo "/var/lib/stsbl/ permissions were ok."
fi

if [ ! -e "/var/lib/stsbl/repoconfig.sh" ]
then
  touch /var/lib/stsbl/repoconfig.sh
  chmod 640 /var/lib/stsbl/repoconfig.sh
  echo "/var/lib/stsbl/repoconfig.sh touched."
else
  echo "/var/lib/stsbl/repoconfig.sh was ok."
fi

if [ $(stat -c "%a" /var/lib/stsbl/repoconfig.sh) != "640" ]
then
  chmod 640 /var/lib/stsbl/repoconfig.sh
  echo "/var/lib/stsbl/repoconfig.sh changed to 640."
else
  echo "/var/lib/stsbl/ permissions were ok."
fi
