Document: stsbl-repoconfig
Title: Debian stsbl-repoconfig Manual
Author: <insert document author here>
Abstract: This manual describes what stsbl-repoconfig is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/stsbl-repoconfig/stsbl-repoconfig.sgml.gz

Format: postscript
Files: /usr/share/doc/stsbl-repoconfig/stsbl-repoconfig.ps.gz

Format: text
Files: /usr/share/doc/stsbl-repoconfig/stsbl-repoconfig.text.gz

Format: HTML
Index: /usr/share/doc/stsbl-repoconfig/html/index.html
Files: /usr/share/doc/stsbl-repoconfig/html/*.html
